# Generated by Django 5.2.12 on 2026-05-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_class_groups_teacher_class_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classgroup'),
        ),
    ]
