# Generated by Django 5.2.12 on 2026-04-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classgroup_student_teacher_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_groups',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classgroup'),
        ),
    ]
